name: Test-Build
on:
  push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra


      - name: Make Directory for results
        run: mkdir -p testResults


      - name: Run POSTMAN collection
        run: |
          newman run example.collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html


      - name: Output the run Details
        uses: actions/upload-artifact@v3
        with:
          name: RunReports
          path: testResults

      - name: Create gh-pages branch if not exists
        run: |
          git fetch origin gh-pages:gh-pages || git checkout --orphan gh-pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: testResults
          force_orphan: true
      #
      #- name: Commit and Push Report
      #  run: |
      #    git add testResults/htmlreport.html
      #    git commit -m "Update test report"
      #    git push origin main